### ISSUE TITLE
날짜 별 Todo 보기 시나리오 작성

### ISSUE THREAD

**Issue by jinlee0** [todoay/api#102]
![image](https://user-images.githubusercontent.com/74762475/182535375-e15e2b6f-3432-4e79-854d-26555363ff11.png)

**Comment by jinlee0** [comment]
![image](https://user-images.githubusercontent.com/74762475/182535375-e15e2b6f-3432-4e79-854d-26555363ff11.png)

**Comment by kgh2120** [comment]
date는 어떤 방식으로 전달하는 거지?? 따로 쓴거면 body로 넘기는건가??

**Comment by jinlee0** [comment]
path parameter인데 ?date={date} 이런 식으로 쓰기 귀찮아서 저렇게 했어. GET은 Body가 없으니까 헷갈리진 않을 거 같아가지구.

**Comment by kgh2120** [comment]
오케이 근데 일반적으로 사용 안하기는 하는데 GET도 바디 넣을 수 있긴해
시나리오 확인
