### ISSUE TITLE
Todo 리스트 정렬 시나리오 작성

### ISSUE THREAD

**Issue by qkrdmswl** [todoay/api#103]
- 정렬 관련 시나리오 (중요도 순, due date 순)

**Comment by qkrdmswl** [comment]
![image](https://user-images.githubusercontent.com/65437087/182765793-7ef8a16c-dc2b-4403-9fdd-ff6fcce2fa57.png)

2,3번에 대해 부연 설명을 하자면, db 정렬할 때 컬럼의 인덱스 번호로도 정렬할 수 있으니까 규현오빠 erd 기준으로 due_date가 1번이었고 importance가 2번 인덱스여서 프론트에서 사용자 선택에 따라 1,2번 구분하고 저렇게 인덱스 번호를 서버로 전달하면 서버가 그대로 그 값으로 order by 하는 시나리오를 생각했어

**Comment by kgh2120** [comment]
어 그런데 어제 entity 클래스 생성한 pr에서 진용이랑 말하면서 쓴거긴 한데 중요도는 그냥 varchar로 저장해서 db사용해서 order by는 따로 못할거같아.
중요도로 정렬하기는 자바로 구현해야 할 거 같아.

시나리오는 확인

**Comment by qkrdmswl** [comment]
아하..그러네
