### ISSUE TITLE
각 자원이 최근 업데이트 된 시간을 저장하는 건 어떨까?

### ISSUE THREAD

**Issue by jinlee0** [todoay/api#110]
## 클라이언트의 데이터 캐싱(?)과 관련한 아이디어.
각 자원이 최근 업데이트 된 시간을 저장하는 건 어떨까?

### 시나리오 ex.
> 클라이언트에서 미리 데이터를 받아놓은 상태에서
> 캘린더의 특정 날짜를 클릭했을 때
> 
> GET /todo/lastUpdatedAt?date=yyyy-MM-dd'T'HH:mm:ss
> response: {lastUpdatedAt} -> 해당 날짜의 나의 Todo들의 updatedAt 중 가장 최근의 updatedAt
> 
> 기존에 저장해놓은 updatedAt과 같으면 그냥 스토리지의 데이터로 보여주고 그 이후면 서버로부터 데이터를 가져와 스토리지 업데이트.

### DB 아이디어 

> 모든 테이블(또는 일부 테이블)에 updatedAt 컬럼을 추가.

**Comment by kgh2120** [comment]
업데이트 기간 같은거 사용하는게 따로 레퍼런스가 있는 거야??

**Comment by kgh2120** [comment]
아래 주소가 스프링부트 캐시사용 하면 나오는 건데 아직 따라 해보지는 않아서 정확하게는 모르겠는데 저런 느낌인거같네??

[https://ssyoni.tistory.com/17](url)
[https://chagokx2.tistory.com/98](url)
[https://www.jiniaslog.co.kr/article/view?articleId=254](url)

**Comment by jinlee0** [comment]
형이 보내준 링크 봤는데 그거는 Spring-DB간에서 Spring이 캐싱을 하는 거 같네.
내가 생각한 건 Client-Server간에서 Client가 캐싱하는 거야.

그리고 updatedAt은 express.js에서 ORM으로 sequelize 쓸 때 자동으로 생성해 주던 거 생각난 거야. [createdAt, updatedAt, deletedAt]

클라이언트에서 데이터를 캐싱하고 있다고 치면 캐싱 데이터 동기화 할 때 생성되거나 수정되거나 삭제된 것만 가져오면 좋을 거 같아서. 이 때 createdAt, updatedAt, deletedAt이 마지막 동기화 시점 이후인 것이 있는 지 검색하고,
없으면 추가 작업 필요 없고
있으면 해당 데이터만 요청하면 되니까
통신 소요가 줄지 않을까 싶음.

**Comment by kgh2120** [comment]
이건 안드로이드 retrofit에서 캐쉬 방법이라는데 캐싱을 내가 안해봐서 정확하게는 모르겠네
[https://jizard.tistory.com/282](url)
[https://bb-library.tistory.com/266](url)

진용이 너가 말하는 방법대로 구현할려면 jpa auditing 기능에 lastModifiedAt 사용하면 쉽게 할 수 있을 거 같긴 해

**Comment by jinlee0** [comment]
오 jpa auditing 이거 물건이네

retrofit 오프라인 캐시도 보니까 설정만 하면 되는 거 같은데 서버 부하도 줄이고 오프라인 환경에서도 앱 이용할 수 있고 좋은 듯.

**Comment by kgh2120** [comment]
![KakaoTalk_20220712_001951892](https://user-images.githubusercontent.com/76154390/182556758-8d37106f-b1c4-4252-a6e1-79add9dc056e.jpg)
