### ISSUE TITLE
비즈니스 로직: 카테고리를 삭제할 때 해당 카테고리의 투두들을 어떻게 해야 할까?

### ISSUE THREAD

**Issue by jinlee0** [todoay/api#111]
1. 해당 카테고리의 투두들도 모두 삭제한다.
2. 해당 카테고리의 투두들의 카테고리를 "일반" 카테고리로 바꾸고 해당 카테고리를 삭제한다.
3. 그 외 어떤 방법이 있을까요?

**Comment by kgh2120** [comment]
투두 메이트의 경우에는 카테고리가 삭제가 2개 방법이 있는데
1. 삭제 -> 지금까지 있던 경우를 모두 삭제한다
2. 종료 -> 지금까지 데이터는 유지하고 앞으로의 화면에서 카테고리가 등장하지 않게 한다
이런 식으로 유지되는데, 이런 방법은 어때??

**Comment by jinlee0** [comment]
오 좋다
그렇게 하려면 Category에 종료 상태(ex. deletedAt, endedAt, ended, state) 같은 걸 둬야하나?

**Comment by kgh2120** [comment]
삭제면 데이터를 싹 날리는거니까 따로 필드를 둘 필요는 없어 보이고 
종료 상태 체크는 있어야 할 거 같은데, date로 관리할 필요 없으면 boolean으로 해도 좋을듯하네

**Comment by LeeChoongHwan** [comment]
그럼 카테고리 관리에서 삭제 방법 2가지 중에서 선택해서 한다는 뜻인거지??

**Comment by kgh2120** [comment]
![image](https://user-images.githubusercontent.com/76154390/182553898-0275e5e9-f85d-4d45-8544-82eaf37847a2.png)
이런느낌

**Comment by LeeChoongHwan** [comment]
오키오키 우리도 그런 느낌으로 해볼게
