### ISSUE TITLE
해시태그 검색 시나리오 작성

### ISSUE THREAD

**Issue by kgh2120** [todoay/api#113]
- 해시태그 검색
    - 기본 흐름
        1. C : Todo 추가 or 수정 화면에서 해시태그 칸을 누르고 값을 입력하고 검색버튼 or 미리보기 리스트의 더보기 버튼 클릭 or 아래로 스크롤을 진행한다.
        2. F : Client가 입력한 값을 아래 url로 전송한다. 
        [GET]/hashtag?name=~~~~
        3. B : PathParmeter로 넘어온 값으로 시작하는 해시태그관련 정보를 N개 담아서 준다.
        body → 해시태그 정보 N개(페이지에 찰 만큼), pagable 객체, hasNext : boolean
        4. F : 해시태그 정보를 리스트 형태로 보여준다. / hasNext가 false일 경우엔 A1. 다음 페이지 검색을 못하게 설정한다.
    - A1. 다음 페이지 검색
        1. C : 검색 결과 더보기 or 아래로 드래그 해서 검색 결과 더 가져오기
        2. F : [POST]/hashtag body{ name, pagable}
        3. 기본 흐름 3 부터 진행
    - A2. 자동 완성 미리보기 검색
        1. C : Todo 추가 or 수정 화면에서 해시태그 칸을 누르고 값을 입력한다. 
        2. F : [GET]/hastag/auto?name=~~~~\
        3. B : PathParameter로 넘어온 값으로 시작하는 해시태그 정보 5개를 넘겨준다
        body : hashtagInfo(id,name)
        4. F : 해시태그 정보를 검색창 밑에 리스트 형태로 보여준다.
    - E1. pagable이 PageRequest의 인스턴스가 아닐 때
        1. C : 다음 페이지가 존재하지 않는데, 다음 페이지 검색을 시도
        2. F :   [POST]/hashtag body{ name, pagable}
        3. B : pagable의 인스턴스가 PageRequest인지 검증 실패 시 NoMoreDateException(403) 반환

노션에도 작성

**Comment by hsh47607** [comment]
굳굳

근데 지금 해시태그 추가에 대해 내 개인적인 UI 구상으로는 두가지가 있는데,
I1. 해시태그 칸 클릭 시 네이버 검색 창(모바일 앱)처럼 화면 전체를 해시태그 검색창으로 전환 / 해당 창에서는 검색에 따른 5개정도의 해시태그만 리스트 / 검색 버튼 클릭 시 키보드를 내리고 해당 페이지에서 입력한 값의 모든 해시태그 정보를 리스트
I2. 해시태그 칸 클릭 시 다이얼로그 형식으로 해시태그 검색창 및 하단에 작은 리스트 창 표현하여 검색에 따른 5개 정보의 해시태그 정보 리스트 / 검색 버튼 클릭 시 전자처럼 키보드를 내리고 화면 전체를 해시태그 검색 결과 리스트 표현
-> 해시태그는 공백을 기준으로 구분되며, 사용자가 입력 후 스페이스바를 클릭하여 공백을 띄우면 해시태그 선택으로 간주하여 검색창을 내리고 해시태그 칸에 표시, 또한 리스트에서 선택 시 검색창을 모두 내리고 선택된 해시태그를 해시태그 칸에 추가

Q. 검색 입력에 따라 5개 정도 데이터를 보여줄 때, 스크롤을 통해 해당 리스트에서 더 보여줄지, 혹은 스크롤을 하면 검색 버튼을 클릭한 것으로 간주하여 입력된 검색 키워드에 대한 모든 리스트를 보여줄지?

참고) 현재 figma에 Todo 추가에 대한 UI를 구성 중인데, 참고해도 좋음. 하지만 아직 내 개인적인 UI일 뿐, 협의된 UI는 아님.

**Comment by kgh2120** [comment]
> Q. 검색 입력에 따라 5개 정도 데이터를 보여줄 때, 스크롤을 통해 해당 리스트에서 더 보여줄지, 혹은 스크롤을 하면 검색 버튼을 클릭한 것으로 간주하여 입력된 검색 키워드에 대한 모든 리스트를 보여줄지?

일반적으로 이런 경우에서는 모든 리스트를 출력하지는 않고, 화면에 보여질 적당한 양만큼만 불러오고 추가적으로 계속 부르는 식으로 로직을 만들어. 우리 프로젝트는 지금 데이터가 별로 없으니까 전체 리스트를 불러오는 게 부담이 없지만, 실제 서비스에서는 데이터가 많은 경우도 고려를 해야 하니까.

**Comment by hsh47607** [comment]
응 5개정도의 데이터를 미리 불러오는 것은 동의. 근데, 입력에 따라 검색되는 검색창(키보드가 존재한 검색창)에서 스크롤을 하면 계속 데이터를 불러오는지? 아님 스크롤을 하는 행위 자체를 검색 버튼을 클릭한 것으로 간주하여 아예 해당 키워드를 검색하여 검색에 대한 전체 리스트를 불러오는지?
이것이 궁금하네

**Comment by kgh2120** [comment]
해시태그 검색 시나리오 수정

-> 기본 흐름의 response body 내용 중 pageable 객체를 nextPageNum:int으로 수정.
-> 기본흐름과 A1을 통합하기 위해 URL 변경 [GET] /hashtag?name=~~~&page=~~~
-> 기본 흐름에서의 URL에서는 page의 값은 0으로 고정.
-> 그 이후 검색의 경우에는 return받은 page값을 쿼리스트링에 입력.

**Comment by kgh2120** [comment]
해시태그 검색 시나리오 수정

각 검색 시 리턴 값에서 id값 삭제
