### ISSUE TITLE
LoginContext

### ISSUE THREAD

**Issue by jinlee0** [todoay/api#133]
기존에 JwtProvider.getLoninId()를 대체해서 LoginContext를 만들어 쓰면 어떨까 싶음.

토큰 필터에서 LoginContext를 세팅해주고 서비스에서 LoginContext.getLoginAuth() 같은 방식으로 쓰기 위함임.

프로토타입 구현해서 PR 올려볼게요.

**Comment by kgh2120** [comment]
@jinlee0  그냥 바로 Auth를 얻고싶어서 그런거야??

**Comment by jinlee0** [comment]
그것도 그렇고 JwtProvider.getLoginId()는 호출할 때마다 data retrieve 하니까 개선해야할 거 같긴 하고. 그리고 JwtProvider에서 로그인 정보를 다루는 건 역할을 벗어나는 거 같아서

**Comment by kgh2120** [comment]
![image](https://user-images.githubusercontent.com/76154390/183251770-1e9a532c-7e53-4bdb-8d70-b7ac2aaeae4b.png)
이게 지금 코드니까 그냥 메서드 위치가 이상하면 클래스만 따로 파서 옮겨도 될 거 같은데, 토큰에서 LoginContext를 세팅할 필요는 없다고 보는게 SecurityContext에 이미 설정을 해놓는거라서 또 해줄 필요는 없을듯??
Auth만 가지고 싶으면 저기서 그냥 Auth를 바로 반환해도 되고

**Comment by jinlee0** [comment]
LoginContext라는 클래스를 추가할 거라 클래스만 새로 파는 거긴 하지. pr 올려볼게. 오늘은 할 건 아니지만 ㅋㅋ
