### ISSUE TITLE
Daily-todo 날짜 별 보기 및 반복 기능 데모 피드백 요청

### ISSUE THREAD

**Issue by kgh2120** [todoay/api#134]
여기에는 코드가 아직 없어서 데모로 구현해봤는데, 한번만 체크점

반복 로직쪽을 좀 깔끔하게 구현하고 싶은데 디자인 패턴쪽을 잘 몰라서 좀 더 공부해보고 나중에 리팩토링 해보겠음.
로직쪽 구현하는 것 훈수 부탁

반복 로직 관련 코드는 SelectOption, RepeatOption, Repeat, Select, DailyRepeat, MonthRepeat, WeeksRepeat, YearRepeat, ThisMonthSelector, OneMonthSelector, CustomNumberSelector, CustomMonthSelector, RepeatService.repeat

전체 코드 [https://github.com/kgh2120/repeatDemo](url)

**날짜별로 보기**
![image](https://user-images.githubusercontent.com/76154390/183252418-706f7eb6-2b54-486d-b681-f3cf3b445401.png)

**반복 생성**
![image](https://user-images.githubusercontent.com/76154390/183252423-3d9bd541-43c7-4647-a8fc-37d2d8e056c5.png)

**반복 로직**
![image](https://user-images.githubusercontent.com/76154390/183252439-53831ae3-6e39-44bc-9ec2-59be9cf2d051.png)

**Comment by jinlee0** [comment]
CustomMonthSelector 같은 경우는 {id}를 가지는 DailyTodo의 날짜를 기준으로 해야 하지 않을까?(현재 날짜 말구)
CustomNumberSelector도 {id}를 가지는 DailyTodo의 날짜를 기준으로.

**Comment by jinlee0** [comment]
ThisMonthSelector일 때 {id}를 가지는 DailyTodo가 '오늘의 이번 달'에 포함 되지 않으면 Bad Request인 것 같기도 하구.

**Comment by kgh2120** [comment]
어.. 예외처리랑 반복설정하는 경우 어떤날짜부터 시작하는지 같은 디테일까지 잡고 만든건 아니고 기능이 돌아가도록 우선적으로 만든거였는데, repeat 메서드 분기하는 방법을 좀 물어보려고 한거였어서

**Comment by jinlee0** [comment]
분기 저렇게 하면 될 거 같음. 더 좋은 방법이 떠오르진 않네.

**Comment by kgh2120** [comment]
반복 기능은 구글 캘린더 로직처럼 하면 되려나?

**Comment by kgh2120** [comment]
옛날 일정에서 반복하면 그날 기준으로 생성하는걸로?

**Comment by jinlee0** [comment]
처음에 시나리오 짤 때 그렇게 생각했어

**Comment by kgh2120** [comment]
근데 Todo는 앞으로 할 것을 체크하는 건데 옛날부터 만드는 거 보다 오늘날부터 추가하는 게 좀 더 맞지 않으려나?? 
요구사항 적인 측면이라서 다른 애들한테도 물어보는 게 좋나?

**Comment by jinlee0** [comment]
다같이 얘기해봐야겠다.
