### ISSUE TITLE
LoginAuthContext - SecurityContextHolder 사용 관련 문제 발생.

### ISSUE THREAD

**Issue by kgh2120** [todoay/api#140]
카테고리를 만든 유저가 해당 카테고리 ID를 사용할 때, 403 코드가 발생하는 문제가 발견되었다.
![image](https://user-images.githubusercontent.com/76154390/184795796-6aa9e823-b416-47a0-bead-b573d8c1d992.png)

원인은 이 메서드를 통과하지 못해서 발생한 거 같은데..
![image](https://user-images.githubusercontent.com/76154390/184795864-9df14bcf-cbda-49e0-9df6-85bda7ea9fb6.png)

여기서 해당 로그를 살펴보면 다음과 같은 값이 나온다.
![image](https://user-images.githubusercontent.com/76154390/184795940-d3747b1a-c4f3-4651-8be7-c2909072ffe4.png)

같은 값을 불러왔는데도 서로 다른 주소를 가지기 때문에 equals 메서드를 재정의 하지 않은 이상 주소가 같은 인스턴스인지 검사하기 때문에 false가 발생한다.

**이는 영속성 컨텍스트와 트랜잭션 범위로 인해 발생하는 문제인데, 서로 다른 트랜잭션은 서로 다른 영속성 컨텍스트를 지니고 있기 때문이다.** SecurityContextHolder는 AuthServiceImpl의 트랜잭션을(jwt토큰을 통해 조회), category는 DailyTodoCRUDServiceImpl의 트랜잭션을(dto.getCategoryId를 통해 repository를 조회) 이용하기 때문에 내용물은 같지만 서로 다른 주소를 가진 auth가 생기게 되는 것이다.

현재 코드가 아래와 같기 때문에 발생하는 문제로 해결하는 방법은 몇 가지 있을 거 같다.
`` if(!category.getAuth().equals(loginAuthContext.getLoginAuth())) throw new NotYourCategoryException();``

#### 3. loginAuthContext에서 Auth를 가져오지 않고 email만 가져와서 사용한다.

만드는 난이도 자체는 거의 비슷해서 결정하기 나름인 거 같고, 결정 되면 내가 작업하고 있는 브랜치에 포함시켜서 진행할께

**Comment by jinlee0** [comment]
2번 한 표
