### ISSUE TITLE
Feat: 내 정보 조회 및 수정

### ISSUE THREAD

**Issue by kgh2120** [todoay/api#23]
### **내 정보 조회 및 수정**

- Access Token의 subject를 분해해서 email 정보를 획득
- ProfileRepository에서 email로 조인해서 profile, email 정보를 획득해온다.  <- Auth에서 해도 같지만, 내 정보 밑에 있는 기능이니 profile에서 하는 것이 맞아보임
- GET의 경우 ResponseDTO 생성해서 반환
- 내 정보 변경의 경우 닉네임, 상메, 프사 정보를 받으면 해당 정보 유효성 검사를 하고,  추가적인 오류 검사(닉네임 중복검사 등..)를 한 이후, 수정.
- 유효성 검사 실패 시 bindException 관련 ErrorResponse, 닉네임 중복 검사 관련으론 Bad_request ErrorResponse 반환
_- 정보 변경의 경우 각각 attribute에 대해서 set method를 사용하는 것 보단 Profile에 update 메서드를 만드는 것은 어떨까 고민.
- Profile에서 nullable한 field(msg, img)의 경우 default 값 설정하는 것은 어떨지 고민._

### **비밀번호 변경 기능**

- Header에서 emailToken 혹은 accessToken을 획득
- token을 분해해서 email 값을 얻는다
- email값을 통해 auth entity를 획득한 이후, body로 받은 새로운 password 를 암호화 해서 비밀번호로 설정.

**Comment by jinlee0** [comment]
회원가입 시 이메일 인증은 **링크**로 하기로 한 것처럼,
비밀번호 변경 시에도 토큰을 사용자에게 직접 전달하기보단 **비밀번호 변경 페이지**를 전달하는 게 어떨까?

**Comment by kgh2120** [comment]
서버에서 클라이언트로 토큰을 전달하는 게 아니라 클라이언트가 서버한테 토큰을 전달하면, 해당 토큰을 통해 Auth 객체를 얻어와서 비밀번호를 변경하는 로직으로 만들려고

**Comment by jinlee0** [comment]
아 이해했다.
