### ISSUE TITLE
Auth no-arg constructor 추가, email 인증 여부 attr 추가

### ISSUE THREAD

**Issue by jinlee0** [todoay/api#26]
### 1. Auth에 기본 생성자 추가
현재 dev 브랜치 기준, Auth에 기본 생성자가 없어서 인텔리제이가 빨간줄을 긋는다.
Entity는 public 또는 protected의 기본 생성자를 가져야 한다.
lombok의 @NoArgsConstructor를 사용하면 편하다.

### 2. Auth에 email 인증 여부를 나타내는 attr 추가 (ex. emailVerified)
용도: 회원가입시 기본적으로 false, 이메일 인증 완료 시 true로 바뀐다.

**Comment by kgh2120** [comment]
Auth에 상태 attribute를 만들어서 예시로 [아무것도 안됨(NONE), 이메일 인증됨(EMAIL_VERIFIED), 생성 완료됨(CREATED), 삭제됨(DELETED).] 이런 식으로 사용하는 건 어떨까?? 이번에 계정 삭제 만드려고 하는데, 삭제할 때 데이터 말소 시키는 게 아니라 상태만 변경하자고 했던 것 같아서

**Comment by jinlee0** [comment]
변수 하나로 인증여부랑 계정상태(생성, 탈퇴 등) 전부 표현하기보단 나누는 게 좋지 않을까?
1. 탈퇴 여부
- LocalDateTime deletedAt 
- null일 경우 탈퇴하지 않음. null이 아닐 경우는 해당 시간에 탈퇴했음을 의미.
2. 생성
- LocalDateTime createdAt 
- 생성시 자동으로 현재 시간 넣음. 이후 변경할 일 없음. <- 현재 굳이 있어야 할 이유는 없는 듯.
3. 이메일 인증 여부
- LocalDateTime emailVerifiedAt
- null일 경우 인증되지 않음. null이 아닐 경우는 해당 시간에 인증되었음을 의미.
