### ISSUE TITLE
feat: 이메일 중복 여부 확인 GET 구현

### ISSUE THREAD

**Issue by jinlee0** [todoay/api#50]
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

기능 이름 | HTTP METHOD | URL | PARAMS | HTTP STATUS | RETURN VALUE
-- | -- | -- | -- | -- | --
이메일 중복 확인 | GET | /auth/email-exists | email: String | 200400 유효성 검사 실패 | emailExists: bool

</body>
</html>

**Comment by kgh2120** [comment]
pr 완료되어서 이슈 종료하겠습니다.
