### ISSUE TITLE
로그인, 회원가입 시 로직 추가, 및 구조 변경, 리팩토링

### ISSUE THREAD

**Issue by kgh2120** [todoay/api#69]
### 회원가입 로직 추가

- 회원 가입 시 입력되는 이메일, 닉네임에 대해서 다시 한 번 중복 검사를 진행함 (중복 검사를 진행 한 값이 아닌 다른 값을 입력할 수 있기 때문에)

### 로그인 로직 추가

- 로그인 할 때 입력받은 계정이 이메일 인증이 완료된 계정인지, 삭제된 계정이 아닌지 체크.

### 구조 변경 및 리팩토링

- ProfileController jwtProvider 의존 삭제
- ProfileServiceImpl에 의존 jwtProvider 추가
- ProfileService에 사용 안하는 parameter 수정
- ServiceImpl class들 중복 코드 리팩토링

**Comment by kgh2120** [comment]
중복 예외의 경우 409 번 코드를 사용한다는 말들이 많아서 변화를 줄지 고민이네

**Comment by jinlee0** [comment]
오 검색해보니 그러네.
회원가입 요청 시 이메일이나 닉넴이 중복이면 409로 던지면 좀 더 명확하겠다.
