### ISSUE TITLE
삭제 로직 추가

### ISSUE THREAD

**Issue by kgh2120** [todoay/api#70]
삭제 시 계정의 정보(이메일, 닉네임, 프사, 상메) 등을 전부 초기화 해 주어야 할 거같음
그렇지 않을 경우 중복 검사에 잡히게 된다.

이메일이나 닉네임은 별 문제가 없다면 uuid로 하거나 무언가 난수를 만드는 방법을 찾아봐야 할 거 같다.

**Comment by jinlee0** [comment]
AuthRepository의 메서드를 커스텀하는건 어떨까?

ex.
findByEmail(Sting email) : deletedAt이 널인 것만
findByEmail(String email, SearchOption option) : option이 SearchOption.ALL이면 전부 ~.DELETED면 삭제된것만

이렇게 spring data jpa에서 되려나??

**Comment by kgh2120** [comment]
entity에 유니크 제약조건 걸어놔서 좀 애매할거 같은데
그런데 전에 나간 계정은 이름도 삭제된 애들처럼 표현하자고 했던거 같아서 그냥 아래 사진같은 애처럼 바꾸는 건 어떨지??
![image](https://user-images.githubusercontent.com/76154390/181051026-7a7165f5-365b-4c05-a134-d73459fb6814.png)

**Comment by jinlee0** [comment]
아 유니크.. 그러네
제약조건 없애기보단
난수 주는 게 좋을 거 같다

**Comment by kgh2120** [comment]
머지되어 종료합니다.
