### ISSUE TITLE
비 로그인 비밀번호 변경, 어떤 방법이 있을까요?

### ISSUE THREAD

**Issue by jinlee0** [todoay/api#74]
1번. 임시 비밀번호 생성
2번. 비밀번호 변경을 위한 이메일 인증여부 필드 추가 ex. passwordChangingRequestedAt
3번. 이메일 인증페이지가 아닌 비밀번호 변경 페이지로 이동하여 해당 html 페이지에서 비밀번호 변경

이외에 어떤 방법이 있을까요?
어떤 방법이 좋을까요?

**Comment by kgh2120** [comment]
개인적으로는 1번 방법이 제일 마음에 드는데 인증 방법이 이메일밖에 없어서 타인이 이메일을 입력해서 비밀번호를 바꿔버릴 수 있다는 단점이 있는 거 같음.

그래서 카카오톡 비밀번호 변경을 찾아서 해봤는데 닉네임 + 이메일로 두 가지를 전부 입력해서  인증 처리를 하네
그래서 이런 방법으로 1번에서 방법을 보완해서 인증번호를 보내건 임시 비밀번호를 전달하는 방식은 어떨까??
![KakaoTalk_20220728_115739488](https://user-images.githubusercontent.com/76154390/181410897-c6c4e4ab-e21d-46e5-bf73-a5f61df88291.jpg)

![image](https://user-images.githubusercontent.com/76154390/181410832-c907dd9a-ee78-4694-a521-0932fa7684d5.png)

**Comment by jinlee0** [comment]
그러네 이메일만 알아도 비밀번호를 임시비번으로 바꿔버릴 수 있구나

**Comment by jinlee0** [comment]
그러면, 
-> 인증 메일 전송 (링크)
-> 링크 누르면 서버에서 임시비밀번호로 변경, 링크 페이지에서 임시비밀번호 알려줌.

임시비밀번호로 변경되는 로직을 한 단계 미루는 거지. 이러면 괜찮나?

**Comment by kgh2120** [comment]
그렇게 해도 좋을듯

**Comment by jinlee0** [comment]
> 그러면, -> 인증 메일 전송 (링크) -> 링크 누르면 서버에서 임시비밀번호로 변경, 링크 페이지에서 임시비밀번호 알려줌.
> 
> 임시비밀번호로 변경되는 로직을 한 단계 미루는 거지. 이러면 괜찮나?

이 방법으로 구현 해보겠습니다.
의견 더 있으면 주세요
