### ISSUE TITLE
내정보 수정(/profile/my) api에서 닉네임 중복체크 해제 요청

### ISSUE THREAD

**Issue by hsh47607** [todoay/api#80]
내정보 수정 api의 updateMyProfile() 내부에서 닉네임 중복체크 예외(NicknameDuplicateException)를 체크하여 발생시키지 않아도 될 듯?

https://github.com/todoay/api/blob/7310f09e7fbd56c7ba2b913d71f894643d8992e1/src/main/java/com/todoay/api/domain/profile/service/ProfileServiceImpl.java#L30-L41

- 클라이언트에서 닉네임 필드 입력에 대해 모든 변화에 따라 닉네임 중복검사 api(/auth/nickname-exists)를 수행
- 따라서 내정보 수정 api(/profile/my) api 호출 시 전달되는 정보(닉네임, 상태메시지, 이미지url) 중 닉네임의 중복검사는 이미 수행된 상태. 즉, 현재 코드에 의하면 닉네임 중복검사를 두 번 수행하는 것
- 어떻게 생각?

- 혹시 변경에 따른 다른 문제가 발생된다고 예측되면 알려줘

**Comment by kgh2120** [comment]
중복 검사를 2번 실행하는 이유는 클라이언트에서 중복 검사를 진행한 이메일로 그대로 정보를 넘겨주지 않을 수 있기 때문이야.

클라이언트에서 중복 검사를 실행한 이메일로 고정되어서 넘겨주려 하겠지만, 해킹을 당하는 등의 문제로 인해서  내 정보 변경과 회원 가입에서도 한번 더 중복 검사를 실행하는거지

**Comment by hsh47607** [comment]
조금 이해가 안되는게, 내정보 변경에서 '클라이언트에서 중복검사를 진행한 이메일로 그대로 정보를 넘겨주지 않을 수 있다'는게 뭐야??

내정보 변경은 토큰으로 유저를 인증한 이후에 진행되는거 아니야? 그리고, 따로 내정보변경할 때 클라이언트에서 이메일을 보내주진 않는데?

**Comment by kgh2120** [comment]
이메일 넘겨준다는건 내가 비밀번호 변경하고 좀 헷갈려서 말을 잘못썻네. 위에 써놓은 거에서 이메일을 닉네임으로 바꿔서 말하면 얘기가 같은데

내 정보 수정에서는 닉네임, 프사, 상메 이렇게 변경을 하는데, 변경하기 이전에 닉네임 중복검사를 진행을 하지.
이때 중복검사한 닉네임하고, [PUT] /profile/my 의 바디로 넘어가는 닉네임하고 다를 수 있기 때문에 한다는 말이었어.

**Comment by hsh47607** [comment]
음. 뭔지 알겠어. 그럼 넘어온 닉네임이 해당 유저의 현재 저장된 닉네임과 동일한 경우에 대해서는 해당 예외를 발생시키지 않는다는 것만 추가해줘.
