### ISSUE TITLE
닉네임에도 패턴 검증을 넣어야하지 않을까

### ISSUE THREAD

**Issue by hseungho** [todoay/api#84]
테스트 하던 중에 깨달은게, 
닉네임 입력할 때, 공백과 특수문자('_'제외)를 입력하지 못하도록 검증해야하지 않을까 싶은데?
어떻게 생각함?

**Comment by kgh2120** [comment]
음 필요하다고 생각하긴 했는데 제약조건의 경우엔 회의를 해야 한다고 생각해서 일단은 공백만 아니게 설정을 해놨어. 나중에 의견을 모아봐야 할거같네
