### ISSUE TITLE
리프레시 토큰 만료에 대한 JWT 토큰에러 status 변경 요청

### ISSUE THREAD

**Issue by hsh47607** [todoay/api#97]
현재 클라이언트에서 401 에러에 대한 모든 response를 /auth/refresh 호출하도록 구성하였어.

그래서 다른 api 호출의 에러 response에 대해서 401 에러는 발생시키지 않도록 해주는 것이 좋아보이고,
리프레시 토큰 만료 시 발생하는 JWT 토큰에러도 현재 401이지만 400으로 변경하는 것이 어떨까 싶은데?

관련 레퍼런스야.
https://stackoverflow.com/questions/55688352/retrofit-handle-refresh-token-expiration

**Comment by jinlee0** [comment]
모든 401 응답에 refresh하기보다 
401일 때 code가 JWT_EXPIRED인 경우에 refresh 하면 어때?

**Comment by jinlee0** [comment]
access token, refresh token 만료일 때 같은 코드(JWT_EXPIRED) 줘서 문제인 거면 ACCESS_JWT_EXPIRED, REFRESH_JWT_EXPIRED 두 경우로 나누면 괜찮나?

**Comment by kgh2120** [comment]
디코에 안들어와있어서 알람 안갈듯?

**Comment by hsh47607** [comment]
음 먼저 모든 api 호출에서 response를 가로채서 그 중 코드가 401일 경우 refresh 하도록 구성하는 것이 좋다는 레퍼런스들이 많았고, 401(Unauthorized)코드는 access token 만료인 경우에만 쓰인다는 레퍼런스도 봤었어서 access token 만료에 대한 경우에만 401을 쓰는 게 좋아보여.

**Comment by hsh47607** [comment]
그리고 위와 같이 처리한 것이 토큰 만료 시 다시 토큰을 발급받아서 다시 해당 api 호출을 하도록 한 것인데, 만약 JWT_EXPIRED 같은 code를 알아내기 위해서는 아예 해당 api 호출을 errorResponse로 받아버린 이후라서 각 api 호출에서 또 다시 해당 api 호출을 하는 것이 과연 좋은 방법일까 싶네...

**Comment by kgh2120** [comment]
url 별로 다른 로직을 적용할 수 없는 상황이면 나는 승호가 말한 방법으로 바꿔도 상관 없을거 같네.
승호가 말한 방식은 이미 코드 상으로는 한번 테스트 해봐서 적용 자체는 바로 할 수 있어.
둘이 뭔가 의견 차이가 있는 것 같으니까 얘기 나누고 결론나면 그거대로 진행하면 될듯하네?

**Comment by jinlee0** [comment]
승호 형 방식으로 하자

**Comment by kgh2120** [comment]
- [ ] Auth - exception - ErrorCode- REFRESH_TOKEN_EXPIRED(400,"리프레쉬 토큰이 만료되었습니다.) < 추가
- [ ] RefreshTokenExpiredException.class 추가
- [ ] RefreshTokenServiceImpl.refreshTokens method에 validateToken 부분에서 try-catch로 ExpiredJwtException 잡아서 위에 생성한 Exception으로 Throw
하는 식으로 바꿔서 올릴께

**Comment by hsh47607** [comment]
ㅇㅋㅇㅋ 모두 고마워!
