### ISSUE TITLE
날짜 반복 설정하기 시나리오 작성

### ISSUE THREAD

**Issue by jinlee0** [todoay/api#99]

**Comment by jinlee0** [comment]
![image](https://user-images.githubusercontent.com/74762475/182540814-54a3d2f5-415c-430d-9f1a-0073151885b3.png)

**Comment by kgh2120** [comment]
repeat 관련 부분이 살짝 모호해보임.
현재 시나리오에서는 개월수로 되어있는거 같은데, 이번달 이라던가 직접 입력(회) 같은 경우도 있으니까 좀 더 세분화하는게 좋아보임

**Comment by jinlee0** [comment]
![image](https://user-images.githubusercontent.com/74762475/182777540-31cb0d18-bfc2-45cd-adee-5ab9e87c7e4a.png)
![image](https://user-images.githubusercontent.com/74762475/182777469-d63ff69b-02c0-444a-9753-a6a22161a16a.png)

**Comment by kgh2120** [comment]
![image](https://user-images.githubusercontent.com/76154390/183247397-4ff60655-7896-4fcb-a6f9-b5ebb478458e.png)
내용 수정
